export interface ShowroomItem {
  id: number;
  title: string;
  description: string;
  room: string;
  style: string;
  area: string;
  materials: string[];
  image: string;
  designer: string;
  features: string[];
  aspectRatio?: "tall" | "wide" | "square";
  color?: string;
  videoUrl?: string;
}

export interface ExampleImage {
  src: string;
  label: string;
  spec?: { title: string; items: string[] };
}

export interface ExampleProject {
  id: string;
  title: string;
  description: string;
  style: string;
  area: string;
  rooms: string;
  stagesCompleted: string;
  link: string;
  gradient: string;
  images: ExampleImage[];
}

const CDN = "https://cdn.poehali.dev/projects/eb3c2b09-4839-4fa9-b212-eefee1635ef8/files";

export const showroomItems: ShowroomItem[] = [
  {
    id: 1,
    title: "Каррара Люкс",
    description: "Ванная с отделкой под белый мрамор каррара, отдельно стоящей ванной и тёплым освещением",
    room: "Ванная",
    style: "Современная классика",
    area: "12 м²",
    materials: ["Керамогранит под мрамор", "Дерево", "Стекло"],
    image: "https://cdn.poehali.dev/projects/eb3c2b09-4839-4fa9-b212-eefee1635ef8/files/09c068e9-03d2-46b3-bcf0-1f9182bdc187.jpg",
    designer: "Студия АВАНГАРД",
    features: ["Тёплый пол", "LED-подсветка", "Отдельно стоящая ванна"],
    aspectRatio: "tall",
    color: "#e8ddd4",
  },
  {
    id: 2,
    title: "Минимал Грей",
    description: "Минималистичная ванная с крупноформатным серым керамогранитом и walk-in душем",
    room: "Ванная",
    style: "Минимализм",
    area: "8 м²",
    materials: ["Крупноформатный керамогранит", "Стекло", "Металл"],
    image: "https://cdn.poehali.dev/projects/eb3c2b09-4839-4fa9-b212-eefee1635ef8/files/0aac2ec0-ac64-4daf-b079-e0173b853691.jpg",
    designer: "Студия АВАНГАРД",
    features: ["Walk-in душ", "Парящая тумба", "Зеркало с подсветкой"],
    aspectRatio: "square",
    color: "#d0d0d0",
  },
  {
    id: 3,
    title: "Белый Остров",
    description: "Просторная кухня с островом из белого мрамора, подвесными светильниками и фартуком ёлочкой",
    room: "Кухня",
    style: "Современный",
    area: "18 м²",
    materials: ["Мрамор", "МДФ эмаль", "Плитка ёлочка"],
    image: "https://cdn.poehali.dev/projects/eb3c2b09-4839-4fa9-b212-eefee1635ef8/files/698fa3f8-0321-4d14-abf9-1eb8ac6ab988.jpg",
    designer: "Студия АВАНГАРД",
    features: ["Остров с мойкой", "Подвесные светильники", "Скрытая техника"],
    aspectRatio: "wide",
    color: "#f5f0e8",
  },
  {
    id: 4,
    title: "Сканди Лайт",
    description: "Уютная гостиная в скандинавском стиле со светлым деревом и максимумом естественного света",
    room: "Гостиная",
    style: "Скандинавский",
    area: "22 м²",
    materials: ["Паркетная доска дуб", "Текстиль", "Натуральный камень"],
    image: "https://cdn.poehali.dev/projects/eb3c2b09-4839-4fa9-b212-eefee1635ef8/files/f7f0934a-4006-4e7b-98a1-7d9ec8f1713c.jpg",
    designer: "Студия АВАНГАРД",
    features: ["Панорамные окна", "Камин", "Зонирование"],
    aspectRatio: "tall",
    color: "#e8e4d8",
  },
  {
    id: 5,
    title: "Индустриал Коппер",
    description: "Брутальная ванная в стиле лофт с бетонными стенами, медной фурнитурой и террацо",
    room: "Ванная",
    style: "Лофт",
    area: "10 м²",
    materials: ["Бетон", "Террацо", "Медь", "Кирпич"],
    image: "https://cdn.poehali.dev/projects/eb3c2b09-4839-4fa9-b212-eefee1635ef8/files/332b4986-7362-4c74-8b40-01c69e1522fb.jpg",
    designer: "Студия АВАНГАРД",
    features: ["Медная фурнитура", "Террацо пол", "Кирпичный акцент"],
    aspectRatio: "square",
    color: "#c4b5a0",
  },
  {
    id: 6,
    title: "Тёплый Уют",
    description: "Спальня в тёплых бежевых тонах с мягким изголовьем и текстурными стеновыми панелями",
    room: "Спальня",
    style: "Современный",
    area: "16 м²",
    materials: ["Стеновые панели", "Текстиль", "Ковровое покрытие"],
    image: "https://cdn.poehali.dev/projects/eb3c2b09-4839-4fa9-b212-eefee1635ef8/files/cdd3d76e-7f03-4f22-9769-755341153243.jpg",
    designer: "Студия АВАНГАРД",
    features: ["Мягкое изголовье", "Подвесные светильники", "Шумоизоляция"],
    aspectRatio: "tall",
    color: "#ddd0c4",
  },
  {
    id: 7,
    title: "Лофт гостиная",
    description: "Open-space гостиная-кухня с кирпичными стенами и высокими потолками",
    room: "Гостиная",
    style: "Лофт",
    area: "40 м²",
    materials: ["Кирпич", "Бетон", "Металл", "Дерево"],
    image: `${CDN}/b089e9d3-b001-48b7-ac81-7b9a30297ef6.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Высокие потолки", "Открытая планировка", "Индустриальные светильники"],
    aspectRatio: "wide",
    color: "#c8b8a8",
  },
  {
    id: 8,
    title: "Детская мечта",
    description: "Яркая детская комната с кроватью-чердаком, меловой стеной и игровой зоной",
    room: "Детская",
    style: "Современный",
    area: "12 м²",
    materials: ["Массив берёзы", "Пробковый пол", "Краска меловая"],
    image: `${CDN}/1492e921-ccc4-4bdd-93a0-c80b2e8496b5.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Кровать-чердак", "Меловая стена", "Рабочий стол"],
    aspectRatio: "square",
    color: "#d4e8d4",
  },
  {
    id: 9,
    title: "Спальня лофт",
    description: "Спальня в индустриальном стиле с бетонной стеной и зеркальными фасадами шкафа",
    room: "Спальня",
    style: "Лофт",
    area: "20 м²",
    materials: ["Декоративная штукатурка", "Зеркальные фасады", "Текстиль"],
    image: `${CDN}/7697134e-6769-4bd4-a06f-a5c9f3f67c13.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Бетонный акцент", "Шкаф-купе", "Портьеры"],
    aspectRatio: "tall",
    color: "#b8b8c0",
  },
  {
    id: 10,
    title: "Кухня в лофте",
    description: "Кухня лофт-апартаментов с медной фурнитурой, деревянными фасадами и кирпичным фартуком",
    room: "Кухня",
    style: "Лофт",
    area: "20 м²",
    materials: ["Массив дуба", "Медь", "Кирпич"],
    image: `${CDN}/a5173987-89c1-4d8a-87a4-047a8c58ea4b.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Кирпичный фартук", "Медные акценты", "Дубовые фасады"],
    aspectRatio: "wide",
    color: "#c8a888",
  },
  {
    id: 11,
    title: "Классика Пресни",
    description: "Гостиная-кухня с белыми матовыми фасадами, кварцевой столешницей и серым диваном",
    room: "Гостиная",
    style: "Современная классика",
    area: "30 м²",
    materials: ["МДФ эмаль", "Кварц", "Велюр"],
    image: `${CDN}/7ce2426a-abfc-4cdb-ac82-68429155aed4.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Остров", "ТВ-стена с рейками", "LED-подсветка"],
    aspectRatio: "tall",
    color: "#e8e8e4",
  },
  {
    id: 12,
    title: "Детская скандинавская",
    description: "Светлая детская в скандинавском стиле с натуральными материалами и уютными текстилями",
    room: "Детская",
    style: "Скандинавский",
    area: "14 м²",
    materials: ["Дерево", "Текстиль", "Хлопок"],
    image: `${CDN}/d0346ac4-9678-44af-b97a-e6276c6f92fc.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Натуральные материалы", "Игровая зона", "Книжные полки"],
    aspectRatio: "square",
    color: "#e0d8cc",
  },
  {
    id: 13,
    title: "Ванная лофт апарт",
    description: "Ванная лофт-апартаментов с чёрной сантехникой, террацо и открытыми полками",
    room: "Ванная",
    style: "Лофт",
    area: "7 м²",
    materials: ["Террацо", "Металл чёрный", "Бетон"],
    image: `${CDN}/3d667c3d-49c9-4501-8050-42148decc8fd.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Чёрная сантехника", "Открытые полки", "Плитка террацо"],
    aspectRatio: "tall",
    color: "#a8a8a0",
  },
  {
    id: 14,
    title: "Кухня Пресни",
    description: "Светлая кухня с островом, барными стульями в велюре и фартуком кабанчик",
    room: "Кухня",
    style: "Скандинавский",
    area: "16 м²",
    materials: ["МДФ", "Кварц под мрамор", "Кабанчик"],
    image: `${CDN}/4a322713-ca93-458b-910e-5039ed94d8a0.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Остров", "Барные стулья", "Плитка кабанчик"],
    aspectRatio: "wide",
    color: "#ece8e0",
  },
  {
    id: 15,
    title: "Спальня скандинавская",
    description: "Воздушная спальня с текстильным изголовьем, тюлем и шторами в тёплых серых тонах",
    room: "Спальня",
    style: "Скандинавский",
    area: "18 м²",
    materials: ["Текстиль", "Дерево", "Хлопок"],
    image: `${CDN}/c49e96bc-9750-48b5-944d-b92b8291e476.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Мягкое изголовье", "Тюль + портьеры", "Гардеробная"],
    aspectRatio: "tall",
    color: "#d8d4cc",
  },
  {
    id: 16,
    title: "Гостиная лофт",
    description: "Гостиная с кожаным диваном, кирпичной стеной и индустриальными светильниками",
    room: "Гостиная",
    style: "Лофт",
    area: "35 м²",
    materials: ["Кожа", "Кирпич", "Сталь", "Дерево"],
    image: `${CDN}/d3fd03ce-2d08-4d61-a40a-b25633298557.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Кожаный диван", "Кирпич", "Стальные рейки"],
    aspectRatio: "square",
    color: "#b8a898",
  },
  {
    id: 17,
    title: "Дзен-ванная",
    description: "Ванная в стиле japandi с отдельно стоящей ванной Bette Lux Shape, плиткой Ragno Realstone и золотой фурнитурой Axor Montreux",
    room: "Ванная",
    style: "Japandi",
    area: "14 м²",
    materials: ["Ragno Realstone Slate 120×240 см", "Ванна Bette Lux Shape", "Смеситель Axor Montreux brushed gold", "Тумба Duravit из дерева"],
    image: `${CDN}/c077ca52-8340-4dad-ad8d-f71f18dfcfa4.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Отдельно стоящая ванна", "Золотая фурнитура Axor", "Spa-атмосфера", "Тёплый пол"],
    aspectRatio: "tall",
    color: "#d4c8b8",
  },
  {
    id: 18,
    title: "Ваби-саби спальня",
    description: "Спальня в стиле wabi-sabi с матрасом Vispring Signatory, бельгийским льном Libeco и светильником Flos IC Light",
    room: "Спальня",
    style: "Japandi",
    area: "20 м²",
    materials: ["Матрас Vispring Signatory", "Постельное бельё Libeco Belgian linen", "Светильник Flos IC Light", "Паркет Barlinek дуб ёлочка", "Травертиновые столешницы"],
    image: `${CDN}/c889585e-72b6-4f9a-a33b-9911d7b85475.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Матрас Vispring", "Barlinek дуб ёлочка", "Льняной текстиль Libeco", "Известковая штукатурка"],
    aspectRatio: "wide",
    color: "#d8d0c4",
  },
  {
    id: 19,
    title: "Арт-деко гостиная",
    description: "Гостиная в стиле арт-деко с изумрудным диваном Poliform Bellport, столиком Eichholtz и светильником Artemide Tolomeo",
    room: "Гостиная",
    style: "Современная классика",
    area: "38 м²",
    materials: ["Диван Poliform Bellport (изумрудный бархат)", "Столик Eichholtz Cartlon (латунь)", "Светильник Artemide Tolomeo", "Паркет Kahrs дуб шеврон", "Ковёр Brabbu геометрика"],
    image: `${CDN}/305989de-d66d-4672-a8a8-02e1cd0f725b.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Poliform Bellport", "Латунные акценты Eichholtz", "Паркет шеврон Kahrs", "Мраморный камин"],
    aspectRatio: "tall",
    color: "#2d5a3d",
  },
  {
    id: 20,
    title: "Чёрная жемчужина",
    description: "Тёмная ванная с плиткой Marazzi Grande black 160×320 см, умывальником Duravit DuraSquare и смесителем Hansgrohe Axor Citterio",
    room: "Ванная",
    style: "Современный",
    area: "11 м²",
    materials: ["Плитка Marazzi Grande Stone Look Marble Black 160×320 см", "Умывальник Duravit DuraSquare", "Смеситель Hansgrohe Axor Citterio matte black", "Полотенцесушитель графит", "Зеркало Antonio Lupi с подсветкой"],
    image: `${CDN}/bec6b488-6163-4246-bb75-d95da2f28095.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Marazzi Grande 160×320 см", "Axor Citterio matte black", "Зеркало Antonio Lupi", "Душ без бортика"],
    aspectRatio: "square",
    color: "#1a1a22",
  },
  {
    id: 21,
    title: "Неоклассика Люкс",
    description: "Гостиная в неоклассическом стиле с диваном Minotti Freeman, креслом Baxter Chester Moon и люстрой Venini из муранского стекла",
    room: "Гостиная",
    style: "Современная классика",
    area: "45 м²",
    materials: ["Диван Minotti Freeman (серый букле)", "Кресло Baxter Chester Moon", "Столик Fendi Casa (мрамор)", "Люстра Venini Poliedri Murano glass", "Паркет Coswick Versailles дуб"],
    image: `${CDN}/91524940-1264-4d25-a7f0-fd4de5427fc0.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Minotti Freeman sofa", "Люстра Venini муранское стекло", "Паркет Coswick Versailles", "Лепной карниз"],
    aspectRatio: "wide",
    color: "#e8e0d4",
  },
  {
    id: 22,
    title: "Полифорум спальня",
    description: "Спальня с гардеробной системой Poliform Senzafine, изголовьем De Padova и ковром Beni Ourain ручной работы",
    room: "Спальня",
    style: "Современный",
    area: "24 м²",
    materials: ["Гардеробная Poliform Senzafine (рифлёное стекло)", "Изголовье De Padova (серый бархат)", "Ковёр Beni Ourain шерсть ручной работы", "Паркет Dinesen дуб", "Светильник Vibia Wireflow"],
    image: `${CDN}/16f31d40-c9a9-44a3-ad1e-1ec350259fad.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Poliform Senzafine", "De Padova изголовье", "Ковёр Beni Ourain", "Паркет Dinesen"],
    aspectRatio: "tall",
    color: "#c8c0b8",
  },
  {
    id: 23,
    title: "Биофилик-ванная",
    description: "Эко-ванная с ванной Agape Spoon, мозаикой Porcelanosa, душем Grohe Rainshower и живой стеной из мха",
    room: "Ванная",
    style: "Эко",
    area: "13 м²",
    materials: ["Ванна Agape Spoon (белый)", "Душ Grohe Rainshower rainfall", "Мозаика Porcelanosa Nature Stone", "Тиковая скамья", "Панель из живого мха"],
    image: `${CDN}/2e5e82b9-df16-4fd2-b478-e0461a707902.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Ванна Agape Spoon", "Душ Grohe Rainshower", "Живая стена из мха", "Тиковое дерево"],
    aspectRatio: "square",
    color: "#8aa888",
  },
  {
    id: 24,
    title: "Дзен-гостиная",
    description: "Гостиная в стиле японди с диваном Muuto Rest, столиком Ethnicraft и светильником Akari Исаму Ногути",
    room: "Гостиная",
    style: "Japandi",
    area: "28 м²",
    materials: ["Диван Muuto Rest (тёмно-зелёная шерсть)", "Столик Ethnicraft тик", "Светильник Akari Isamu Noguchi (рисовая бумага)", "Ширма shoji", "Бетонный пол"],
    image: `${CDN}/a493762c-b14e-4a4c-b7f3-b10c6c8a1403.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Muuto Rest diван", "Akari Noguchi lamp", "Ширма shoji", "Татами-ковёр"],
    aspectRatio: "tall",
    color: "#6a7a68",
  },
  {
    id: 25,
    title: "Максималист спальня",
    description: "Яркая спальня с шёлковой кроватью Savoir Beds No5, обоями Fornasetti Nuvolette и персидским ковром ручной работы",
    room: "Спальня",
    style: "Современная классика",
    area: "22 м²",
    materials: ["Кровать Savoir Beds No5 (бирюзовый шёлк)", "Обои Fornasetti Nuvolette", "Персидский ковёр ручной работы", "Текстиль Loro Piana cashmere", "Прикроватные лампы с цветными абажурами"],
    image: `${CDN}/5f7e8cc2-4c3b-4fc6-b9f1-d3426067a244.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Savoir Beds No5", "Обои Fornasetti", "Персидский ковёр", "Кашемир Loro Piana"],
    aspectRatio: "wide",
    color: "#5a4a7a",
  },
  {
    id: 26,
    title: "Ванная Прованс",
    description: "Ванная во французском классическом стиле с ванной Lefroy Brooks La Chapelle, плиткой Porcelanosa Antique и смесителями Gessi",
    room: "Ванная",
    style: "Современная классика",
    area: "16 м²",
    materials: ["Ванна Lefroy Brooks La Chapelle (эмаль)", "Плитка Porcelanosa Antique cream", "Двойной умывальник Roca Carmen на мраморной консоли", "Зеркала Villeroy & Boch с позолоченными рамами", "Мраморный пол ёлочкой"],
    image: `${CDN}/c5122ab9-6625-41a0-a24f-e1bea333e15e.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Lefroy Brooks ванна", "Roca Carmen умывальник", "Pozолоченные зеркала V&B", "Мрамор ёлочкой"],
    aspectRatio: "tall",
    color: "#e4d8c8",
  },
  {
    id: 27,
    title: "Скандинавский лаундж",
    description: "Светлая гостиная с диваном HAY Mags, стульями Fritz Hansen Series 7 и светильником Muuto Unfold",
    room: "Гостиная",
    style: "Скандинавский",
    area: "32 м²",
    materials: ["Диван HAY Mags (пыльно-розовая ткань)", "Стулья Fritz Hansen Series 7", "Светильник Muuto Unfold", "Стеллаж Bolia дуб", "Джутовый ковёр", "Бетонный пол"],
    image: `${CDN}/ee3942ae-2103-47d8-8568-9f850b972ef6.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["HAY Mags sofa", "Fritz Hansen Series 7", "Muuto Unfold lamp", "Стеллаж Bolia"],
    aspectRatio: "square",
    color: "#d4c4bc",
  },
  {
    id: 28,
    title: "Трансишн спальня",
    description: "Спальня переходного стиля с кроватью Tempur-Pedic, бельём RH Linen и встроенными гардеробными с рифлёными дубовыми фасадами",
    room: "Спальня",
    style: "Современный",
    area: "26 м²",
    materials: ["Кровать Tempur-Pedic (бежевый велюр)", "Постельное бельё RH Linen", "Плед Loro Piana cashmere", "Встроенные гардеробные с фасадами рифлёный дуб", "Прикроватные лампы Ralph Lauren Home", "Паркет дуб копчёный ёлочка"],
    image: `${CDN}/4ac0d958-e968-4946-b6e5-dadff7aff596.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Tempur-Pedic", "RH Linen бельё", "Loro Piana плед", "Ralph Lauren лампы"],
    aspectRatio: "tall",
    color: "#d0c8b8",
  },
  {
    id: 29,
    title: "Итальянская ванная",
    description: "Ванная в итальянском стиле с тумбой Antonio Lupi, сантехникой Flaminia Link, смесителями Gessi rose gold и плиткой Atlas Concorde Calacatta",
    room: "Ванная",
    style: "Современный",
    area: "15 м²",
    materials: ["Тумба Antonio Lupi (Corian белый)", "Унитаз Flaminia Link подвесной", "Смеситель Gessi (rose gold)", "Плитка Atlas Concorde Marvel Stone Calacatta", "Ниша с LED-подсветкой", "Душ без бортика с панорамным стеклом"],
    image: `${CDN}/9a58065f-dfea-44cf-a26c-2729fe3b87ee.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Antonio Lupi тумба", "Gessi rose gold", "Atlas Concorde Calacatta", "Flaminia Link"],
    aspectRatio: "wide",
    color: "#f0e8e0",
  },
  {
    id: 30,
    title: "Индустриальный шик",
    description: "Гостиная industrial chic с секционным диваном RH Maxwell, подвесными светильниками Arteriors Edison и металлическим стеллажом во всю высоту",
    room: "Гостиная",
    style: "Лофт",
    area: "42 м²",
    materials: ["Диван RH Maxwell (серая перформанс-ткань)", "Светильники Arteriors Edison (кластер)", "Кресла Cassina 633 Barcelona (чёрная кожа)", "Ковёр Moooi Carpets геометрика", "Открытый бетонный потолок", "Кирпичная стена акцент"],
    image: `${CDN}/ed6d90e6-95f5-40d8-8be9-9954d32ee22d.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["RH Maxwell диван", "Arteriors Edison lights", "Cassina Barcelona кресла", "Moooi ковёр"],
    aspectRatio: "tall",
    color: "#6a6460",
  },
  {
    id: 31,
    title: "Прибрежная спальня",
    description: "Спальня в coastal-стиле с плетёным изголовьем Serena & Lily, постельным бельём Riviera Maison и занавесками Kravet Sunbrella",
    room: "Спальня",
    style: "Скандинавский",
    area: "19 м²",
    materials: ["Изголовье Serena & Lily (ротанг)", "Постельное бельё Riviera Maison (чистый лён)", "Занавески Kravet Sunbrella linen", "Прикроватные лампы Arteriors (дрейфвуд)", "Джутовый ковёр", "Деревянные тумбы из плавника"],
    image: `${CDN}/6a91a51f-2f53-4d22-ba84-f6ce1349b107.jpg`,
    designer: "Студия АВАНГАРД",
    features: ["Serena & Lily ротанг", "Riviera Maison linen", "Kravet Sunbrella шторы", "Arteriors лампы"],
    aspectRatio: "square",
    color: "#c8d4d8",
  },
];

export const roomFilters = ["Все", "Ванная", "Кухня", "Гостиная", "Спальня", "Детская"];
export const styleFilters = ["Все", "Современная классика", "Минимализм", "Japandi", "Эко", "Современный", "Скандинавский", "Лофт"];

export const exampleProjects: ExampleProject[] = [
  {
    id: "presnya",
    title: "Двухкомнатная квартира на Пресне",
    description: "Полный дизайн-проект в современном стиле: планировка, визуализации, чертежи, подбор материалов и декор. Посмотрите, как выглядит готовый результат работы конструктора.",
    style: "Современный",
    area: "65 м²",
    rooms: "3 комнаты",
    stagesCompleted: "7/7",
    link: "/designer/planning?project=4",
    gradient: "from-primary/5 to-transparent",
    images: [
      { src: `${CDN}/7ce2426a-abfc-4cdb-ac82-68429155aed4.jpg`, label: "Планировка квартиры", spec: { title: "Планировка 65 м²", items: ["Гостиная-кухня — 30 м² (открытая планировка)", "Спальня — 18 м² (с гардеробной 6 м²)", "Детская — 12 м² (игровая + рабочая зона)", "Коридор — 5 м² (хранение обуви и одежды)", "Высота потолков — 270 см", "Количество окон — 6"] } },
      { src: `${CDN}/7697134e-6769-4bd4-a06f-a5c9f3f67c13.jpg`, label: "Обмерный план", spec: { title: "Обмерный план гостиной-кухни", items: ["Размеры помещения — 650 × 450 см", "Дверь — 90 × 200 см (стена 450 см, отступ 20 см)", "Окно — 150 × 120 см (стена 650 см, отступ 50 см)", "Остров — 120 × 200 см в центре кухни", "Кухонный гарнитур — 300 см вдоль стены", "Угловой диван — 250 см"] } },
      { src: `${CDN}/3d667c3d-49c9-4501-8050-42148decc8fd.jpg`, label: "Развёртки стен", spec: { title: "Развёртки 4 стен", items: ["Стена 1 (650 см) — ниша для техники 150 × 100 см, h=70 см", "Стена 2 (450 см) — окно 150 см на высоте 120 см", "Стена 3 (650 см) — встроенный шкаф 200 × 250 см", "Стена 4 (450 см) — дверь 90 см + ниша 90 см", "Стены 1, 3 — гипсокартон, краска светло-серая", "Стены 2, 4 — кирпич, светлый керамогранит"] } },
      { src: `${CDN}/4a322713-ca93-458b-910e-5039ed94d8a0.jpg`, label: "План полов", spec: { title: "План полов 29,25 м²", items: ["Гостиная (15 м²) — ламинат дуб, 8 мм", "Кухня (14,25 м²) — серый керамогранит, 10 мм", "Уровень пола — 0 см (единый)", "Ламинат — 700 ₽/м², итого 10 500 ₽", "Керамогранит — 1 200 ₽/м², итого 17 100 ₽"] } },
      { src: `${CDN}/c49e96bc-9750-48b5-944d-b92b8291e476.jpg`, label: "План потолков", spec: { title: "План потолков и освещения", items: ["Высота потолка — 300 см", "Гостиная — LED-лента по периметру, споты через 150 см", "Кухня — 4 светильника 10W над рабочей зоной, h=250 см", "Светильники — 500 ₽/шт × 8 = 4 000 ₽", "Сценарии: общий, рабочий, акцентный"] } },
      { src: `${CDN}/b089e9d3-b001-48b7-ac81-7b9a30297ef6.jpg`, label: "Гостиная-кухня", spec: { title: "Визуализация гостиной-кухни", items: ["Белые матовые фасады, кварцевая столешница под мрамор", "Остров с барными стульями в сером велюре", "Фартук — плитка «кабанчик», серая затирка", "Серый угловой диван, мраморный журнальный стол", "ТВ-стена — дубовые рейки + LED-подсветка", "Палитра: белый 60%, дуб 20%, серый 15%, олива 5%"] } },
      { src: `${CDN}/1492e921-ccc4-4bdd-93a0-c80b2e8496b5.jpg`, label: "Спальня", spec: { title: "Визуализация спальни", items: ["Мягкое текстильное изголовье", "Подвесные светильники-шары у кровати", "Стена за кроватью — декоративная штукатурка под бетон", "Шкаф-купе — зеркальные + дубовые фасады", "Шторы: тюль + портьеры тёплый серый", "Зона — 12 м² спальная + 6 м² гардеробная"] } },
      { src: `${CDN}/d0346ac4-9678-44af-b97a-e6276c6f92fc.jpg`, label: "Детская", spec: { title: "Визуализация детской", items: ["Кровать-чердак из массива берёзы", "Рабочий стол с полками внизу", "Стена с меловой краской для рисования", "Стеллаж с яркими корзинами", "Пол — пробка + ковёр с геометрией", "Акценты: жёлтый и мятный"] } },
    ],
  },
  {
    id: "loft",
    title: "Лофт-апартаменты на Красном Октябре",
    description: "Брутальный индустриальный интерьер: кирпичные стены, бетонные потолки, медная фурнитура и тёплое дерево. Открытая планировка с зонированием светом.",
    style: "Лофт",
    area: "85 м²",
    rooms: "3 комнаты",
    stagesCompleted: "7/7",
    link: "/designer/planning?project=4",
    gradient: "from-orange-50 to-transparent",
    images: [
      { src: `${CDN}/d3fd03ce-2d08-4d61-a40a-b25633298557.jpg`, label: "Планировка", spec: { title: "Планировка 85 м²", items: ["Гостиная-кухня-столовая — 40 м² (open space)", "Спальня — 20 м² (с собственным санузлом)", "Кабинет — 15 м² (домашний офис)", "Ванная — 5 м² (душ + террацо)", "Коридор — 5 м²", "Фабричные окна во всю стену"] } },
      { src: `${CDN}/a5173987-89c1-4d8a-87a4-047a8c58ea4b.jpg`, label: "Развёртки стен", spec: { title: "Развёртки стен кухни", items: ["Фартук — кирпич ручной формовки, белая затирка", "Гарнитур — массив дуба, тёмное масло", "Фурнитура — медь матовая", "Вытяжка — встроенная в полку, медный короб", "Полка открытая — 200 × 30 см, дуб", "Смеситель — медный, высокий излив"] } },
      { src: `${CDN}/332b4986-7362-4c74-8b40-01c69e1522fb.jpg`, label: "Ванная", spec: { title: "Ванная комната 5 м²", items: ["Пол — террацо, тёплый серый", "Стены — бетонная штукатурка, матовая", "Душ — walk-in, 90×90 см", "Смеситель + лейка — чёрный матовый металл", "Зеркало — круглое, d=60 см", "Полотенцесушитель — медь"] } },
      { src: `${CDN}/b089e9d3-b001-48b7-ac81-7b9a30297ef6.jpg`, label: "Гостиная", spec: { title: "Визуализация гостиной", items: ["Диван — кожа натуральная, коньяк", "Стена — кирпич ручной формовки", "Потолок — бетон, h=380 см", "Светильники — индустриальные, металл + стекло", "Ковёр — джут, 250×350 см", "Стол — металл + стекло калёное"] } },
      { src: `${CDN}/cdd3d76e-7f03-4f22-9769-755341153243.jpg`, label: "Спальня", spec: { title: "Визуализация спальни", items: ["Кровать — металлический каркас, чёрный", "Изголовье — кожаные панели, тёмно-серый", "Пол — паркетная доска дуб, тёмное масло", "Текстиль — лён + хлопок, серо-бежевый", "Шкаф — распашной, массив дуба", "Светильники — бра медь матовая"] } },
      { src: `${CDN}/7697134e-6769-4bd4-a06f-a5c9f3f67c13.jpg`, label: "Кабинет", spec: { title: "Домашний офис 15 м²", items: ["Стол — массив дуба, 200×80 см", "Кресло — кожа натуральная", "Стеллаж — металл + дерево, h=240 см", "Подсветка — споты направленные", "Акустика — панели из войлока на стене", "Пол — ковровое покрытие серое"] } },
    ],
  },
  {
    id: "scandi",
    title: "Скандинавская квартира на Чистых прудах",
    description: "Светлый семейный интерьер с натуральным деревом, льняным текстилем и живыми растениями. Минимум лишнего, максимум уюта.",
    style: "Скандинавский",
    area: "72 м²",
    rooms: "3 комнаты",
    stagesCompleted: "7/7",
    link: "/designer/planning?project=4",
    gradient: "from-green-50 to-transparent",
    images: [
      { src: `${CDN}/f7f0934a-4006-4e7b-98a1-7d9ec8f1713c.jpg`, label: "Гостиная", spec: { title: "Гостиная 24 м²", items: ["Диван — угловой, лён натуральный, светло-серый", "Кофейный стол — дуб + металл белый", "ТВ-зона — открытые полки дуб", "Пол — ламинат дуб беленый, 10 мм", "Ковёр — шерсть, 200×300 см, молочный", "Растения — фикус, монстера, суккуленты"] } },
      { src: `${CDN}/4a322713-ca93-458b-910e-5039ed94d8a0.jpg`, label: "Кухня", spec: { title: "Кухня 16 м²", items: ["Фасады — МДФ краска, белый матовый", "Столешница — кварц под мрамор Каррара", "Фартук — плитка кабанчик, белый глянец", "Остров — 120×80 см, дуб + белый", "Барные стулья — велюр серый, 2 шт", "Техника — встроенная, нержавеющая сталь"] } },
      { src: `${CDN}/c49e96bc-9750-48b5-944d-b92b8291e476.jpg`, label: "Спальня", spec: { title: "Спальня 18 м²", items: ["Кровать — 160×200 см, каркас дуб", "Изголовье — мягкое, лён дымчатый", "Шкаф-купе — 240 см, фасады эмаль белая", "Прикроватные тумбы — дуб, 2 шт", "Шторы — блэкаут + тюль, серо-бежевый", "Гардеробная — 4 м², встроенная"] } },
      { src: `${CDN}/d0346ac4-9678-44af-b97a-e6276c6f92fc.jpg`, label: "Детская", spec: { title: "Детская 14 м²", items: ["Кровать — массив берёзы, 90×200 см", "Рабочая зона — стол + полки", "Стеллаж — белый, 80×200 см", "Пол — пробка натуральная", "Ковёр — хлопок, геометрический принт", "Декор — натуральные материалы"] } },
      { src: `${CDN}/09c068e9-03d2-46b3-bcf0-1f9182bdc187.jpg`, label: "Ванная", spec: { title: "Ванная 8 м²", items: ["Ванна — отдельностоящая, белый акрил", "Пол — керамогранит под камень", "Стены — плитка белая глянец 30×60", "Тумба — дерево беленое, 2 ящика", "Зеркало — с подсветкой, 80×60 см", "Смеситель — матовый хром"] } },
      { src: `${CDN}/0aac2ec0-ac64-4daf-b079-e0173b853691.jpg`, label: "Санузел", spec: { title: "Санузел 4 м²", items: ["Душевая — walk-in, 100×100 см", "Стены — крупный формат 60×120, серый", "Пол — мозаика антислип, серый", "Тумба парящая — дерево беленое", "Смеситель — чёрный матовый", "Полотенцесушитель — белый"] } },
    ],
  },
  {
    id: "minimal",
    title: "Студия-минимализм на Патриарших",
    description: "Компактная студия 42 м² с японским минимализмом: серый бетон, белые стены, дерево и полное отсутствие лишнего. Каждый предмет на своём месте.",
    style: "Минимализм",
    area: "42 м²",
    rooms: "1 комната",
    stagesCompleted: "7/7",
    link: "/designer/planning?project=4",
    gradient: "from-gray-50 to-transparent",
    images: [
      { src: `${CDN}/0aac2ec0-ac64-4daf-b079-e0173b853691.jpg`, label: "Общий вид", spec: { title: "Студия 42 м²", items: ["Жилая зона — 25 м² (гостиная + спальня)", "Кухонная зона — 10 м²", "Санузел — 5 м²", "Коридор — 2 м²", "Высота потолков — 310 см", "Окна — панорамные, 2 шт × 180 см"] } },
      { src: `${CDN}/3d667c3d-49c9-4501-8050-42148decc8fd.jpg`, label: "Ванная", spec: { title: "Санузел 5 м²", items: ["Пол — крупный формат 60×120, серый матовый", "Стены — бетонная штукатурка декоративная", "Душ — walk-in, 100×90 см, стекло 8 мм", "Инсталляция — скрытый бачок", "Тумба парящая — h=50 см, белый лак", "Смеситель — матовый хром"] } },
      { src: `${CDN}/698fa3f8-0321-4d14-abf9-1eb8ac6ab988.jpg`, label: "Кухня", spec: { title: "Кухонная зона 10 м²", items: ["Гарнитур — белый матовый, без ручек", "Столешница — искусственный камень белый", "Фартук — стекло закалённое, белое", "Варочная панель — индукция 60 см", "Холодильник — встроенный, панель под фасад", "Мойка — накладная, нержавеющая"] } },
      { src: `${CDN}/cdd3d76e-7f03-4f22-9769-755341153243.jpg`, label: "Спальная зона", spec: { title: "Спальная зона", items: ["Кровать — платформа низкая, h=25 см", "Матрас — 160×200 см, ортопедический", "Изголовье — стеновые панели дуб, 200 см", "Текстиль — хлопок 100%, белый + серый", "Освещение — споты на треке", "Зонирование — занавеска лён"] } },
      { src: `${CDN}/7ce2426a-abfc-4cdb-ac82-68429155aed4.jpg`, label: "Зона отдыха", spec: { title: "Гостиная зона", items: ["Диван — 2-местный, серый лён", "Кофейный стол — бетон + металл, h=35 см", "Полка — навесная, дуб 120 см", "Медиа-стена — панели дуб + LED-подсветка", "Ковёр — короткий ворс, 160×230 см", "Растения — минимум 2 горшка"] } },
    ],
  },
];