
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS citizenship VARCHAR(100);
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS has_tools BOOLEAN DEFAULT FALSE;
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS work_style VARCHAR(50) DEFAULT 'both';
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS technologies_knowledge TEXT;
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS certificates TEXT[] DEFAULT '{}';
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS portfolio_photos TEXT[] DEFAULT '{}';
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS portfolio_links TEXT[] DEFAULT '{}';
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS payment_methods TEXT[] DEFAULT '{}';
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS payment_schedule VARCHAR(50);
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS discount_info TEXT;
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS business_status VARCHAR(50);
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS profile_completed BOOLEAN DEFAULT FALSE;
ALTER TABLE contractors ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE contractors ALTER COLUMN company_name SET DEFAULT '';
