CREATE TABLE user_plans (
  id SERIAL PRIMARY KEY,
  code VARCHAR(20) UNIQUE NOT NULL,
  name VARCHAR(100) NOT NULL,
  segment VARCHAR(10) NOT NULL,
  price INTEGER NOT NULL,
  is_monthly BOOLEAN NOT NULL DEFAULT FALSE,
  max_projects INTEGER NOT NULL DEFAULT 1,
  max_visualizations INTEGER NOT NULL DEFAULT 3,
  max_revisions INTEGER NOT NULL DEFAULT 0,
  has_materials BOOLEAN NOT NULL DEFAULT FALSE,
  has_suppliers BOOLEAN NOT NULL DEFAULT FALSE,
  has_brief BOOLEAN NOT NULL DEFAULT FALSE,
  has_manager BOOLEAN NOT NULL DEFAULT FALSE,
  has_crm BOOLEAN NOT NULL DEFAULT FALSE,
  has_whitelabel BOOLEAN NOT NULL DEFAULT FALSE,
  is_unlimited BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);